# Generated by Django 5.2.9 on 2025-12-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rebuild_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maniuser',
            name='nickname',
        ),
    ]
