# Generated by Django 5.2.9 on 2025-12-17 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic_remove_course_level_course_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.topic'),
        ),
    ]
