# Generated by Django 5.2.9 on 2025-12-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='options_json',
            field=models.TextField(blank=True, default='[]', help_text='Для choice и cards: варианты ответа (текст или image url)'),
        ),
    ]
