# Generated by Django 5.2.9 on 2025-12-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_progress_all_correct_progress_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.CharField(max_length=1000),
        ),
    ]
